{
	'name': 'Gestion Budgetaire',
	'author': 'Telia Informatique',
	'version': "1.0",
	'depends': ['base', 'Referentiel_Global'],
	'description': 'Gestion Budgetaire',
	'images': ['static/description/budget.jpg'],
	'summary': "Gestion Budgetaire",
	'data': ['security/budget_security.xml',
			 'views/budget.xml',
			 'views/budget_p.xml',
			 'views/budget_p_traitement.xml',
			 'views/ppm.xml',
			 'views/report_budget.xml',
			 'security/ir.model.access.csv',
			 'data/budg_data.xml'],
	'installable': True,
	'auto_install': False,
}
