{
    "name": "Gestion des prêts",
    "version": "1.0",
    "author": "TELIA INFORMATIQUE",
    "depends":[
        "Referentiel_Global",
        "mail",
        # 'base_geolocalize',
        # 'web_google_maps',
        # 'google_marker_icon_picker',
        'web_digital_sign'
    ],
    "data":[
        'security/security.xml',
        'security/restricted_company_rule.xml',
        "security/ir.model.access.csv",
        'wizard/credit_wizard.xml',
        "views/donnees.xml",
        "views/parametres.xml",
        "views/credit_user_affectation.xml",
        "views/client.xml",
        "views/credit.xml",
        "views/projet_programme.xml",
        "views/credit_membre.xml",
        "views/credit_comite.xml",
        "views/credit_prog_deblocage.xml",
        "views/cpt_exploitation.xml",
        "views/credit_edition.xml",
        "views/credit_garantie.xml",
        "views/credit_prog_rest_fa.xml",
        "views/credit_remboursement.xml",
        "views/credit_pv.xml",
        "views/credit_transfert.xml",
        "views/credit_annulation.xml",
        "views/credit_recouvrement.xml",
        "views/credit_mod_libre.xml",
        "views/credit_synthese.xml",
        "views/menus.xml",
        "report/rembourssement_report.xml",
        "report/credit_report.xml",
        "report/credit_edition.xml",
        "report/credit_synthese.xml",
        "report/credit_pv.xml",
        "report/credit_recouvrement.xml",
        "report/credit_prog_deblocage.xml",
        "data/data.xml",
    ],
    "application": True,
    "category": "FAARF",
    "Summary": "Gestion des prêts",
    "installable": True,
    "auto_install": False,
}
