{
    'name': 'Comptabilité',
    'author': 'Telia Informatique',
    'version': "1.0",
    'depends': ['base', 'faarf_budget', 'faarf_credit'],
    'description': 'Gestion de la comptabilité',
    'images': ['static/description/compta.jpg'],
    'summary': "Gestion de la Comptabilité",
    'data': ['security/compta_security.xml',
             'views/typec.xml',
             'views/compta.xml',
             'views/compta_p.xml',
             'views/report_compta.xml',
             'data/compta_data.xml', 'security/ir.model.access.csv', ],
    'installable': True,
    'auto_install': False,
}
